# $target_urls << 'http://china.alibaba.com/company/detail/hfcyznkj.html'
# $target_urls << 'http://china.alibaba.com/company/detail/rxtza.html'
# $target_urls << 'http://china.alibaba.com/company/detail/yixintuxiang.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hosenliu.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zflfve.html'
# $target_urls << 'http://china.alibaba.com/company/detail/scsw888888.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xphome2010.html'
# $target_urls << 'http://china.alibaba.com/company/detail/ouxunkeji.html'
# $target_urls << 'http://china.alibaba.com/company/detail/bzlidan.html'
# $target_urls << 'http://china.alibaba.com/company/detail/daweinet88.html'
# $target_urls << 'http://china.alibaba.com/company/detail/cg314382808.html'
# $target_urls << 'http://china.alibaba.com/company/detail/a6226851.html'
# $target_urls << 'http://china.alibaba.com/company/detail/rey125815917.html'
# $target_urls << 'http://china.alibaba.com/company/detail/kexinkeleba.html'
# $target_urls << 'http://china.alibaba.com/company/detail/ebodu2009.html'
# $target_urls << 'http://china.alibaba.com/company/detail/chenyifeisam.html'
# $target_urls << 'http://china.alibaba.com/company/detail/b2b-685771035.html'
# $target_urls << 'http://china.alibaba.com/company/detail/niuqcheng.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hf114cc.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zhoubingwu.html'
# $target_urls << 'http://china.alibaba.com/company/detail/sanlong006.html'
# $target_urls << 'http://china.alibaba.com/company/detail/kuyosa.html'
# $target_urls << 'http://china.alibaba.com/company/detail/tenhisi.html'
# $target_urls << 'http://china.alibaba.com/company/detail/tupanyue.html'
# $target_urls << 'http://china.alibaba.com/company/detail/qiyingwangluo.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wydljj090202.html'
# $target_urls << 'http://china.alibaba.com/company/detail/bbmh.html'
# $target_urls << 'http://china.alibaba.com/company/detail/yingbao256194.html'
# $target_urls << 'http://china.alibaba.com/company/detail/sunjian20110303.html'
# $target_urls << 'http://china.alibaba.com/company/detail/jz110jlb.html'

# $target_urls << 'http://china.alibaba.com/company/detail/jz110jlb.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wtt6870073.html'
# $target_urls << 'http://china.alibaba.com/company/detail/aqmywl2011.html'
# $target_urls << 'http://china.alibaba.com/company/detail/eqihang2010.html'
# $target_urls << 'http://china.alibaba.com/company/detail/licailine.html'
# $target_urls << 'http://china.alibaba.com/company/detail/win654.html'
# $target_urls << 'http://china.alibaba.com/company/detail/anhui5732292.html'
# $target_urls << 'http://china.alibaba.com/company/detail/baidulilingfeng.html'
# $target_urls << 'http://china.alibaba.com/company/detail/bozhouzhongwangkeji.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xjj4332.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wh111net.html'
# $target_urls << 'http://china.alibaba.com/company/detail/yc510481838.html'
# $target_urls << 'http://china.alibaba.com/company/detail/bo261708553.html'
# $target_urls << 'http://china.alibaba.com/company/detail/yy59150.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wangjinlong0821.html'
# $target_urls << 'http://china.alibaba.com/company/detail/anhuhefei.html'
# $target_urls << 'http://china.alibaba.com/company/detail/masdlkj.html'
# $target_urls << 'http://china.alibaba.com/company/detail/sunxinnet.html'
# $target_urls << 'http://china.alibaba.com/company/detail/nickx102743379.html'
# $target_urls << 'http://china.alibaba.com/company/detail/niuniu0420.html'
# $target_urls << 'http://china.alibaba.com/company/detail/ahsxld.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zhangyebao.html'
# $target_urls << 'http://china.alibaba.com/company/detail/chulei396.html'
# $target_urls << 'http://china.alibaba.com/company/detail/cnbaiyun2011.html'
# $target_urls << 'http://china.alibaba.com/company/detail/fzkj2011.html'
# $target_urls << 'http://china.alibaba.com/company/detail/ahhs1973.html'
# $target_urls << 'http://china.alibaba.com/company/detail/ahwzw.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xw317865024.html'
# $target_urls << 'http://china.alibaba.com/company/detail/ciyan888.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hefeiguyue.html'

# $target_urls << 'http://china.alibaba.com/company/detail/hirgo.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wahfoon.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xwj594128.html'
# $target_urls << 'http://china.alibaba.com/company/detail/mastcgs.html'
# $target_urls << 'http://china.alibaba.com/company/detail/lbchenlei.html'
# $target_urls << 'http://china.alibaba.com/company/detail/tanshusheng84.html'
# $target_urls << 'http://china.alibaba.com/company/detail/anhuizhuansong.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hfxianan.html'
# $target_urls << 'http://china.alibaba.com/company/detail/followyourheart.html'
# $target_urls << 'http://china.alibaba.com/company/detail/bairuomeng.html'
# $target_urls << 'http://china.alibaba.com/company/detail/anxiake.html'
# $target_urls << 'http://china.alibaba.com/company/detail/keyou88.html'
# $target_urls << 'http://china.alibaba.com/company/detail/jiateng2788.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zhujunjian1108.html'
# $target_urls << 'http://china.alibaba.com/company/detail/edusji.html'
# $target_urls << 'http://china.alibaba.com/company/detail/sanlong002.html'
# $target_urls << 'http://china.alibaba.com/company/detail/nanpyta.html'
# $target_urls << 'http://china.alibaba.com/company/detail/song978.html'
# $target_urls << 'http://china.alibaba.com/company/detail/lsb580.html'
# $target_urls << 'http://china.alibaba.com/company/detail/topinok.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hfjsys.html'
# $target_urls << 'http://china.alibaba.com/company/detail/yanhaixx.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wcjz168.html'
# $target_urls << 'http://china.alibaba.com/company/detail/joyceppbb.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zhxunis.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zhuleimin9999.html'
# $target_urls << 'http://china.alibaba.com/company/detail/dreamgoods88.html'
# $target_urls << 'http://china.alibaba.com/company/detail/janny223.html'
# $target_urls << 'http://china.alibaba.com/company/detail/fang322521.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wanglili201010.html'

$target_urls << 'http://china.alibaba.com/company/detail/tianmawangluo2012.html'
$target_urls << 'http://china.alibaba.com/company/detail/bktaohui111.html'
$target_urls << 'http://china.alibaba.com/company/detail/qiuapp.html'
$target_urls << 'http://china.alibaba.com/company/detail/ahjinuo.html'
$target_urls << 'http://china.alibaba.com/company/detail/fxtx8888.html'
$target_urls << 'http://china.alibaba.com/company/detail/baiduherry.html'
$target_urls << 'http://china.alibaba.com/company/detail/bjjt13685515932.html'
$target_urls << 'http://china.alibaba.com/company/detail/chaoren6.html'
$target_urls << 'http://china.alibaba.com/company/detail/superstar201007.html'
$target_urls << 'http://china.alibaba.com/company/detail/zml2141066.html'
$target_urls << 'http://china.alibaba.com/company/detail/lingduchuanmei.html'
$target_urls << 'http://china.alibaba.com/company/detail/senlier2008.html'
$target_urls << 'http://china.alibaba.com/company/detail/huoyuni.html'
$target_urls << 'http://china.alibaba.com/company/detail/shyf2012.html'
$target_urls << 'http://china.alibaba.com/company/detail/romantic0058.html'
$target_urls << 'http://china.alibaba.com/company/detail/jinnuo84.html'
$target_urls << 'http://china.alibaba.com/company/detail/mhbl1800.html'
$target_urls << 'http://china.alibaba.com/company/detail/wsf702.html'
$target_urls << 'http://china.alibaba.com/company/detail/caodoudou1990.html'
$target_urls << 'http://china.alibaba.com/company/detail/xuzy09.html'
$target_urls << 'http://china.alibaba.com/company/detail/m356150570.html'
$target_urls << 'http://china.alibaba.com/company/detail/philini.html'
$target_urls << 'http://china.alibaba.com/company/detail/lion874340352.html'
$target_urls << 'http://china.alibaba.com/company/detail/itycl.html'






