# $target_urls << 'http://china.alibaba.com/company/detail/zww6428372.html'
# $target_urls << 'http://china.alibaba.com/company/detail/b2b-500224147.html'
# $target_urls << 'http://china.alibaba.com/company/detail/a80808088.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zznseo.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xunke2010.html'
# $target_urls << 'http://china.alibaba.com/company/detail/lcxwebcn123.html'
# $target_urls << 'http://china.alibaba.com/company/detail/chiyurong.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xueni1490.html'
# $target_urls << 'http://china.alibaba.com/company/detail/luohan520.html'
# $target_urls << 'http://china.alibaba.com/company/detail/yosan520.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xuanqiwangxunwangluo.html'
# $target_urls << 'http://china.alibaba.com/company/detail/tianyigo2009.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xmbaizi2009.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zhaomengjieshop.html'
# $target_urls << 'http://china.alibaba.com/company/detail/qwqw343.html'
# $target_urls << 'http://china.alibaba.com/company/detail/pawad6428.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xmboyism.html'
# $target_urls << 'http://china.alibaba.com/company/detail/haojing2012.html'
# $target_urls << 'http://china.alibaba.com/company/detail/fk300120120407.html'
# $target_urls << 'http://china.alibaba.com/company/detail/you000s.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wellknownvis.html'
# $target_urls << 'http://china.alibaba.com/company/detail/mimi5201314520.html'
# $target_urls << 'http://china.alibaba.com/company/detail/myths2010.html'
# $target_urls << 'http://china.alibaba.com/company/detail/fudemy.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zpxyad.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xiangxiaohua789.html'
# $target_urls << 'http://china.alibaba.com/company/detail/sonia1985111.html'
# $target_urls << 'http://china.alibaba.com/company/detail/lwx550.html'
# $target_urls << 'http://china.alibaba.com/company/detail/pl6518353.html'
# $target_urls << 'http://china.alibaba.com/company/detail/yuyryx.html'
# $target_urls << 'http://china.alibaba.com/company/detail/liaichubb.html'
# $target_urls << 'http://china.alibaba.com/company/detail/keerbaobao2007.html'
# $target_urls << 'http://china.alibaba.com/company/detail/marslbg.html'
# $target_urls << 'http://china.alibaba.com/company/detail/fzsbht.html'
# $target_urls << 'http://china.alibaba.com/company/detail/b2b-20422712.html'
# $target_urls << 'http://china.alibaba.com/company/detail/liuronghua1988.html'
# $target_urls << 'http://china.alibaba.com/company/detail/cbyilong.html'
# $target_urls << 'http://china.alibaba.com/company/detail/babyfeng89.html'
# $target_urls << 'http://china.alibaba.com/company/detail/shuaikugame.html'
# $target_urls << 'http://china.alibaba.com/company/detail/niqun00.html'
# $target_urls << 'http://china.alibaba.com/company/detail/qq604221602.html'
# $target_urls << 'http://china.alibaba.com/company/detail/julicm.html'
# $target_urls << 'http://china.alibaba.com/company/detail/inruiart.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zjqjack.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xbdljx.html'
# $target_urls << 'http://china.alibaba.com/company/detail/fzddcm.html'
# $target_urls << 'http://china.alibaba.com/company/detail/kewang02008.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hehewozixin.html'
# $target_urls << 'http://china.alibaba.com/company/detail/taozhen1986.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xi46598406.html'
# $target_urls << 'http://china.alibaba.com/company/detail/pear80707713.html'
# $target_urls << 'http://china.alibaba.com/company/detail/ginniao.html'
# $target_urls << 'http://china.alibaba.com/company/detail/web1566.html'
# $target_urls << 'http://yi777111888.cn.alibaba.com/'
# $target_urls << 'http://haidicheng.cn.alibaba.com/'
# $target_urls << 'http://china.alibaba.com/company/detail/socantv.html'
# $target_urls << 'http://china.alibaba.com/company/detail/lanyunjin.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hrccb.html'
# $target_urls << 'http://china.alibaba.com/company/detail/razor2007.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zsq641.html'

$target_urls << 'http://china.alibaba.com/company/detail/fzjayi.html'
$target_urls << 'http://china.alibaba.com/company/detail/good68yes.html'
$target_urls << 'http://china.alibaba.com/company/detail/yawendesign.html'
$target_urls << 'http://china.alibaba.com/company/detail/soco1312.html'
$target_urls << 'http://china.alibaba.com/company/detail/xiamenjuli.html'
$target_urls << 'http://china.alibaba.com/company/detail/jayguiji.html'
$target_urls << 'http://china.alibaba.com/company/detail/kairui37.html'
$target_urls << 'http://china.alibaba.com/company/detail/woaishuwen.html'
$target_urls << 'http://china.alibaba.com/company/detail/misspalyboy.html'
$target_urls << 'http://china.alibaba.com/company/detail/bendigong.html'
$target_urls << 'http://china.alibaba.com/company/detail/hxznt2010.html'
$target_urls << 'http://china.alibaba.com/company/detail/zfnet0591.html'
$target_urls << 'http://china.alibaba.com/company/detail/atxsoft.html'
$target_urls << 'http://china.alibaba.com/company/detail/zp3ix.html'
$target_urls << 'http://china.alibaba.com/company/detail/cycaliww.html'
$target_urls << 'http://china.alibaba.com/company/detail/fzkrwh.html'
$target_urls << 'http://china.alibaba.com/company/detail/zzrjm.html'
$target_urls << 'http://china.alibaba.com/company/detail/z5237812.html'
$target_urls << 'http://china.alibaba.com/company/detail/echoshow.html'
$target_urls << 'http://china.alibaba.com/company/detail/xmhaona.html'
$target_urls << 'http://china.alibaba.com/company/detail/fzlong2011.html'
$target_urls << 'http://china.alibaba.com/company/detail/lnest2004.html'
$target_urls << 'http://china.alibaba.com/company/detail/guxuepiaohan.html'
$target_urls << 'http://china.alibaba.com/company/detail/dgt3d.html'
$target_urls << 'http://china.alibaba.com/company/detail/chaseyou2011.html'
$target_urls << 'http://china.alibaba.com/company/detail/dyzon2010.html'
$target_urls << 'http://china.alibaba.com/company/detail/fuzhoujinyang.html'
$target_urls << 'http://china.alibaba.com/company/detail/sharpmedia.html'
$target_urls << 'http://china.alibaba.com/company/detail/zhoujuanjuan123.html'
$target_urls << 'http://china.alibaba.com/company/detail/qigeshejigs.html'
$target_urls << 'http://china.alibaba.com/company/detail/yixueer9999.html'
$target_urls << 'http://china.alibaba.com/company/detail/xmyt2000.html'
$target_urls << 'http://china.alibaba.com/company/detail/estarad.html'
$target_urls << 'http://china.alibaba.com/company/detail/liyifujia123.html'
$target_urls << 'http://china.alibaba.com/company/detail/zhaoriling.html'
$target_urls << 'http://china.alibaba.com/company/detail/iantex.html'
$target_urls << 'http://china.alibaba.com/company/detail/podase001.html'
$target_urls << 'http://china.alibaba.com/company/detail/sytying.html'
$target_urls << 'http://china.alibaba.com/company/detail/xmxiangyan.html'
$target_urls << 'http://china.alibaba.com/company/detail/ctwanlong.html'
$target_urls << 'http://china.alibaba.com/company/detail/fjcylzl.html'
$target_urls << 'http://china.alibaba.com/company/detail/wto114.html'
$target_urls << 'http://china.alibaba.com/company/detail/juxiang99.html'
$target_urls << 'http://china.alibaba.com/company/detail/czj0614.html'
$target_urls << 'http://china.alibaba.com/company/detail/xmok7.html'
$target_urls << 'http://china.alibaba.com/company/detail/ldf999.html'
