# $target_urls << 'http://china.alibaba.com/company/detail/derrickcui.html'
# $target_urls << 'http://china.alibaba.com/company/detail/dltopsoft2010.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xdinc.html'
# $target_urls << 'http://china.alibaba.com/company/detail/chinese100e.html'
# $target_urls << 'http://china.alibaba.com/company/detail/medaguan.html'
# $target_urls << 'http://china.alibaba.com/company/detail/80510572.html'
# $target_urls << 'http://china.alibaba.com/company/detail/liltad.html'
# $target_urls << 'http://china.alibaba.com/company/detail/10014250.html'
# $target_urls << 'http://china.alibaba.com/company/detail/jiefengsoft.html'
# $target_urls << 'http://china.alibaba.com/company/detail/slulu8.html'
# $target_urls << 'http://china.alibaba.com/company/detail/chedonghai.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xanyu1996.html'
# $target_urls << 'http://china.alibaba.com/company/detail/chrismanmartin2011.html'
# $target_urls << 'http://china.alibaba.com/company/detail/jungyil.html'
# $target_urls << 'http://china.alibaba.com/company/detail/kexin122488.html'
# $target_urls << 'http://china.alibaba.com/company/detail/tianshidejuli.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xinmeijie2010.html'
# $target_urls << 'http://china.alibaba.com/company/detail/yanjingshefc.html'
# $target_urls << 'http://china.alibaba.com/company/detail/sy182.html'
# $target_urls << 'http://china.alibaba.com/company/detail/chaoyuewangluo521.html'
# $target_urls << 'http://china.alibaba.com/company/detail/isaaq83.html'
# $target_urls << 'http://china.alibaba.com/company/detail/psy9988.html'
# $target_urls << 'http://china.alibaba.com/company/detail/ykfxfz.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wangli8303081014.html'
# $target_urls << 'http://china.alibaba.com/company/detail/liuchengweinet.html'
# $target_urls << 'http://china.alibaba.com/company/detail/gangchengwang.html'
# $target_urls << 'http://china.alibaba.com/company/detail/googlehost.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zfb051920129.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hezhenkeji.html'
# $target_urls << 'http://china.alibaba.com/company/detail/steelkx123.html'

# $target_urls << 'http://china.alibaba.com/company/detail/daliantianhong.html'
# $target_urls << 'http://china.alibaba.com/company/detail/fuyu19861017.html'
# $target_urls << 'http://china.alibaba.com/company/detail/chushuren.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zhynethome.html'
# $target_urls << 'http://china.alibaba.com/company/detail/iasn.html'
# $target_urls << 'http://china.alibaba.com/company/detail/yaoyue0504.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zhuantou4.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zengxinyu555.html'
# $target_urls << 'http://china.alibaba.com/company/detail/sy400.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wangcong201006.html'
# $target_urls << 'http://china.alibaba.com/company/detail/sknoa.html'
# $target_urls << 'http://china.alibaba.com/company/detail/oklop.html'
# $target_urls << 'http://china.alibaba.com/company/detail/maleface.html'
# $target_urls << 'http://china.alibaba.com/company/detail/nichiwa00.html'
# $target_urls << 'http://china.alibaba.com/company/detail/dlxingdakeji2011.html'
# $target_urls << 'http://china.alibaba.com/company/detail/yiqing1980.html'
# $target_urls << 'http://china.alibaba.com/company/detail/allenzhensu.html'
# $target_urls << 'http://china.alibaba.com/company/detail/nabory.html'
# $target_urls << 'http://china.alibaba.com/company/detail/pyf0001.html'
# $target_urls << 'http://china.alibaba.com/company/detail/buyaobeipan.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hefeiwangluojishu.html'
# $target_urls << 'http://china.alibaba.com/company/detail/rainshady.html'
# $target_urls << 'http://china.alibaba.com/company/detail/daisy1014.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zgdxgg.html'
# $target_urls << 'http://china.alibaba.com/company/detail/pjchangwei.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xc250938513.html'
# $target_urls << 'http://china.alibaba.com/company/detail/quanchengtuwen.html'
# $target_urls << 'http://china.alibaba.com/company/detail/lionxcchina.html'
# $target_urls << 'http://china.alibaba.com/company/detail/dlxingdakeji.html'
# $target_urls << 'http://china.alibaba.com/company/detail/qinyonggang2007.html'

$target_urls << 'http://china.alibaba.com/company/detail/kulehu.html'
$target_urls << 'http://china.alibaba.com/company/detail/wangyihhf.html'
$target_urls << 'http://china.alibaba.com/company/detail/dlaft56.html'
$target_urls << 'http://china.alibaba.com/company/detail/lichengcheng870112.html'
$target_urls << 'http://china.alibaba.com/company/detail/derrickcui.html'
$target_urls << 'http://china.alibaba.com/company/detail/dltopsoft2010.html'
$target_urls << 'http://china.alibaba.com/company/detail/dlfeiyusoft.html'
$target_urls << 'http://china.alibaba.com/company/detail/zhanwenjing1990.html'
$target_urls << 'http://china.alibaba.com/company/detail/totoidc2010.html'
$target_urls << 'http://china.alibaba.com/company/detail/bohai56.html'
$target_urls << 'http://china.alibaba.com/company/detail/xdinc.html'
$target_urls << 'http://china.alibaba.com/company/detail/knowlton.html'
$target_urls << 'http://china.alibaba.com/company/detail/dljinghaikeji.html'
$target_urls << 'http://china.alibaba.com/company/detail/wd1973.html'
$target_urls << 'http://china.alibaba.com/company/detail/chinese100e.html'
$target_urls << 'http://china.alibaba.com/company/detail/jiumahuashan.html'
$target_urls << 'http://china.alibaba.com/company/detail/liyunlong159.html'
$target_urls << 'http://china.alibaba.com/company/detail/sws19.html'
$target_urls << 'http://china.alibaba.com/company/detail/syyjcs02431512995.html'
$target_urls << 'http://china.alibaba.com/company/detail/medaguan.html'
$target_urls << 'http://china.alibaba.com/company/detail/belad5517.html'
$target_urls << 'http://china.alibaba.com/company/detail/js868sms.html'
$target_urls << 'http://china.alibaba.com/company/detail/80510572.html'
$target_urls << 'http://china.alibaba.com/company/detail/tideendless.html'
$target_urls << 'http://china.alibaba.com/company/detail/janni0860.html'
$target_urls << 'http://china.alibaba.com/company/detail/reigocehua.html'
$target_urls << 'http://china.alibaba.com/company/detail/hldzw001.html'
$target_urls << 'http://china.alibaba.com/company/detail/liltad.html'
$target_urls << 'http://china.alibaba.com/company/detail/10014250.html'
$target_urls << 'http://china.alibaba.com/company/detail/weisiyang.html'
$target_urls << 'http://china.alibaba.com/company/detail/jiefengsoft.html'
$target_urls << 'http://china.alibaba.com/company/detail/hsyg713.html'
$target_urls << 'http://china.alibaba.com/company/detail/link024.html'
$target_urls << 'http://china.alibaba.com/company/detail/acty2008.html'
$target_urls << 'http://china.alibaba.com/company/detail/suneva.html'
$target_urls << 'http://china.alibaba.com/company/detail/tangtang0218.html'
$target_urls << 'http://china.alibaba.com/company/detail/tianbianyu1017.html'
$target_urls << 'http://china.alibaba.com/company/detail/wei24545000.html'
$target_urls << 'http://china.alibaba.com/company/detail/lovingcom.html'
$target_urls << 'http://china.alibaba.com/company/detail/warmzoom.html'
$target_urls << 'http://china.alibaba.com/company/detail/huaxiaqimai.html'
$target_urls << 'http://china.alibaba.com/company/detail/soulqq.html'
$target_urls << 'http://china.alibaba.com/company/detail/frenchsnail.html'
$target_urls << 'http://china.alibaba.com/company/detail/lnsdkj.html'
$target_urls << 'http://china.alibaba.com/company/detail/onestoptr.html'
$target_urls << 'http://china.alibaba.com/company/detail/gcah.html'
$target_urls << 'http://china.alibaba.com/company/detail/lcgg138994008.html'
$target_urls << 'http://china.alibaba.com/company/detail/zy3211961.html'
$target_urls << 'http://china.alibaba.com/company/detail/modernbell.html'
$target_urls << 'http://china.alibaba.com/company/detail/asd555896.html'
$target_urls << 'http://china.alibaba.com/company/detail/pink20042008beijing.html'
$target_urls << 'http://china.alibaba.com/company/detail/geniuscui.html'
$target_urls << 'http://china.alibaba.com/company/detail/qubeon.html'
$target_urls << 'http://china.alibaba.com/company/detail/hongpr.html'
$target_urls << 'http://china.alibaba.com/company/detail/dlbtdmt.html'
$target_urls << 'http://china.alibaba.com/company/detail/dldaicom.html'
$target_urls << 'http://china.alibaba.com/company/detail/jujiangguanggao.html'
$target_urls << 'http://china.alibaba.com/company/detail/sreye.html'
$target_urls << 'http://china.alibaba.com/company/detail/guansangang.html'
$target_urls << 'http://china.alibaba.com/company/detail/dlybc.html'
