# $target_urls << 'http://china.alibaba.com/company/detail/snqss.html'
# $target_urls << 'http://china.alibaba.com/company/detail/bushid520.html'
# $target_urls << 'http://china.alibaba.com/company/detail/dangzhuxi.html'
# $target_urls << 'http://china.alibaba.com/company/detail/soafar1.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zhouyu890722.html'
# $target_urls << 'http://china.alibaba.com/company/detail/gouxiaoqiang1.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hocay.html'
# $target_urls << 'http://china.alibaba.com/company/detail/mssqwe.html'
# $target_urls << 'http://china.alibaba.com/company/detail/dol350752107.html'
# $target_urls << 'http://china.alibaba.com/company/detail/n2007yu.html'
# $target_urls << 'http://china.alibaba.com/company/detail/sunnyi56.html'
# $target_urls << 'http://china.alibaba.com/company/detail/liqiang239.html'
# $target_urls << 'http://china.alibaba.com/company/detail/song236591302.html'
# $target_urls << 'http://china.alibaba.com/company/detail/loky5719.html'
# $target_urls << 'http://china.alibaba.com/company/detail/taijics.html'
# $target_urls << 'http://china.alibaba.com/company/detail/oceantechnology.html'
# $target_urls << 'http://china.alibaba.com/company/detail/lalalala2020.html'
# $target_urls << 'http://china.alibaba.com/company/detail/fuxiaogang168.html'
# $target_urls << 'http://china.alibaba.com/company/detail/suodr.html'
# $target_urls << 'http://china.alibaba.com/company/detail/aliweek8.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xieh25.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zg5106595.html'
# $target_urls << 'http://china.alibaba.com/company/detail/mm332684284.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zt870912.html'
# $target_urls << 'http://china.alibaba.com/company/detail/njlihao.html'
# $target_urls << 'http://china.alibaba.com/company/detail/dragonhyl.html'
# $target_urls << 'http://china.alibaba.com/company/detail/chuangxi28.html'
# $target_urls << 'http://china.alibaba.com/company/detail/cold1191.html'
# $target_urls << 'http://china.alibaba.com/company/detail/baiyiwangzhi.html'
# $target_urls << 'http://china.alibaba.com/company/detail/dongfangyuz.html'

# $target_urls << 'http://china.alibaba.com/company/detail/snqss.html'
# $target_urls << 'http://china.alibaba.com/company/detail/zp363386141.html'
# $target_urls << 'http://china.alibaba.com/company/detail/taijics.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xinqunzi5.html'
# $target_urls << 'http://china.alibaba.com/company/detail/scdw2826.html'
# $target_urls << 'http://china.alibaba.com/company/detail/leqijinpin.html'
# $target_urls << 'http://china.alibaba.com/company/detail/lily11206.html'
# $target_urls << 'http://china.alibaba.com/company/detail/cold1191.html'
# $target_urls << 'http://china.alibaba.com/company/detail/nimoyu.html'
# $target_urls << 'http://china.alibaba.com/company/detail/oceantechnology.html'
# $target_urls << 'http://china.alibaba.com/company/detail/aabbzdj.html'
# $target_urls << 'http://china.alibaba.com/company/detail/lalalala2020.html'
# $target_urls << 'http://china.alibaba.com/company/detail/jiangzhiyong999.html'
# $target_urls << 'http://china.alibaba.com/company/detail/pantherzhi.html'
# $target_urls << 'http://china.alibaba.com/company/detail/simepu001.html'
# $target_urls << 'http://china.alibaba.com/company/detail/baiyiwangzhi.html'
# $target_urls << 'http://china.alibaba.com/company/detail/cdbaqianli.html'
# $target_urls << 'http://china.alibaba.com/company/detail/federalink.html'
# $target_urls << 'http://china.alibaba.com/company/detail/dongfangyuz.html'
# $target_urls << 'http://china.alibaba.com/company/detail/qt87678169.html'
# $target_urls << 'http://china.alibaba.com/company/detail/n2007yu.html'
# $target_urls << 'http://china.alibaba.com/company/detail/myrfkj.html'
# $target_urls << 'http://china.alibaba.com/company/detail/xieh25.html'
# $target_urls << 'http://china.alibaba.com/company/detail/guiqikeji.html'
# $target_urls << 'http://china.alibaba.com/company/detail/jianghaozhang.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wlp0.html'
# $target_urls << 'http://china.alibaba.com/company/detail/hu0jincun.html'
# $target_urls << 'http://china.alibaba.com/company/detail/joyousdeswjr.html'
# $target_urls << 'http://china.alibaba.com/company/detail/handou184.html'
# $target_urls << 'http://china.alibaba.com/company/detail/wiwi886655.html'

$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''
$target_urls << ''